### ISSUE TITLE
Alternatives to gurobi?

### ISSUE THREAD

**Issue by colindaven** [at-cg/PHI#12]
Hi,

this tool looks interesting, but use of Gurobi will preclude usage by many, presumbly packaging by bioconda, correctly configured containers etc. Are you looking at other alternatives to Gurobi or do they not really exist?

Thanks

**Comment by gsc74** [comment]
Hi,

Thank you for your interest and feedback!

Currently, the tool supports Gurobi, but we are planning to add support for GLPK in the future (https://www.gnu.org/software/glpk/), which should make it more accessible for a broader audience. Additionally, we aim to provide installation support through bioconda to streamline setup and accessibility.

Best,
Ghanshyam
